apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: three-tier
type: Opaque
stringData:
  username: YWRtaW4= #admin # required field for kubernetes.io/basic-auth
  password: cGFzc3dvcmQxMjM=   #Three-Tier-Project # required field for kubernetes.io/basic-auth